[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Milo"
authors = [{name = "Devang", email = "devang@contriversedge.com"}]
dynamic = ["version", "description"]
